from app.models.base import TimestampMixin, UUIDMixin
from app.models.knowledge import (
    CodeTemplate,
    KnowledgePoint,
    KnowledgePointDifficulty,
    KnowledgePrerequisite,
    Lecture,
    LectureLevel,
)
from app.models.learning import (
    CONSECUTIVE_WA_THRESHOLD,
    MASTERY_THRESHOLD,
    WEAK_MASTERY_THRESHOLD,
    DailyTask,
    DailyTaskItem,
    DailyTaskItemStatus,
    DailyTaskItemType,
    LearningPath,
    LearningPathItem,
    LearningProfile,
    PathItemKind,
    PathItemStatus,
    UserKnowledgeState,
    UserProblemAC,
)
from app.models.problem import (
    Problem,
    ProblemDifficulty,
    ProblemKnowledgePoint,
    ProblemStatus,
    ProblemVariant,
    Solution,
    SolutionComment,
)
from app.models.user import TargetMedal, User, UserRole

__all__ = [
    "TimestampMixin",
    "UUIDMixin",
    "KnowledgePoint",
    "KnowledgePointDifficulty",
    "KnowledgePrerequisite",
    "Lecture",
    "LectureLevel",
    "CodeTemplate",
    "Problem",
    "ProblemDifficulty",
    "ProblemStatus",
    "ProblemKnowledgePoint",
    "ProblemVariant",
    "Solution",
    "SolutionComment",
    # Task 10 学习路径与推送引擎
    "UserKnowledgeState",
    "UserProblemAC",
    "LearningProfile",
    "LearningPath",
    "LearningPathItem",
    "PathItemKind",
    "PathItemStatus",
    "DailyTask",
    "DailyTaskItem",
    "DailyTaskItemStatus",
    "DailyTaskItemType",
    "MASTERY_THRESHOLD",
    "WEAK_MASTERY_THRESHOLD",
    "CONSECUTIVE_WA_THRESHOLD",
    # Task 2 用户认证
    "User",
    "UserRole",
    "TargetMedal",
]
