"""add discussions and wrongbook

Revision ID: 04936a68d35a
Revises: 0006
Create Date: 2026-08-04 06:45:55.796259

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "04936a68d35a"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "discussions",
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "category",
            sa.Enum("general", "question", "experience", "suggestion", name="discussion_category"),
            nullable=False,
        ),
        sa.Column("knowledge_id", sa.UUID(), nullable=True),
        sa.Column("problem_id", sa.UUID(), nullable=True),
        sa.Column("is_pinned", sa.Boolean(), nullable=False),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("like_count", sa.Integer(), nullable=False),
        sa.Column("comment_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["knowledge_id"], ["knowledge_points.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_discussions_author_id"), "discussions", ["author_id"], unique=False)
    op.create_index(op.f("ix_discussions_knowledge_id"), "discussions", ["knowledge_id"], unique=False)
    op.create_index(op.f("ix_discussions_problem_id"), "discussions", ["problem_id"], unique=False)
    op.create_table(
        "discussion_comments",
        sa.Column("discussion_id", sa.UUID(), nullable=False),
        sa.Column("author_id", sa.UUID(), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("parent_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["discussion_id"], ["discussions.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["parent_id"], ["discussion_comments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_discussion_comments_discussion_id"), "discussion_comments", ["discussion_id"], unique=False
    )
    op.create_table(
        "wrongbook_entries",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("submission_id", sa.UUID(), nullable=False),
        sa.Column("problem_id", sa.UUID(), nullable=True),
        sa.Column("verdict", sa.String(length=32), nullable=False),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("last_retry_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["problem_id"], ["problems.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["submission_id"], ["submissions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("submission_id", "user_id", name="uq_wrongbook_submission_user"),
    )
    op.create_index(op.f("ix_wrongbook_entries_problem_id"), "wrongbook_entries", ["problem_id"], unique=False)
    op.create_index(op.f("ix_wrongbook_entries_submission_id"), "wrongbook_entries", ["submission_id"], unique=False)
    op.create_index(op.f("ix_wrongbook_entries_user_id"), "wrongbook_entries", ["user_id"], unique=False)
    op.create_index(op.f("ix_wrongbook_entries_verdict"), "wrongbook_entries", ["verdict"], unique=False)
    op.drop_constraint("uq_codeforces_account_user", "codeforces_accounts", type_="unique")
    op.drop_index("ix_codeforces_accounts_user_id", table_name="codeforces_accounts")
    op.create_index(op.f("ix_codeforces_accounts_user_id"), "codeforces_accounts", ["user_id"], unique=True)
    op.drop_index(
        "uq_learning_paths_active_per_user", table_name="learning_paths", postgresql_where="(is_active = true)"
    )
    op.drop_column("lectures", "embedding")
    op.create_index(op.f("ix_submissions_contest_id"), "submissions", ["contest_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_submissions_contest_id"), table_name="submissions")
    op.add_column("lectures", sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True))
    op.create_index(
        "uq_learning_paths_active_per_user",
        "learning_paths",
        ["user_id"],
        unique=True,
        postgresql_where="(is_active = true)",
    )
    op.drop_index(op.f("ix_codeforces_accounts_user_id"), table_name="codeforces_accounts")
    op.create_index("ix_codeforces_accounts_user_id", "codeforces_accounts", ["user_id"], unique=False)
    op.create_unique_constraint("uq_codeforces_account_user", "codeforces_accounts", ["user_id"])
    op.drop_index(op.f("ix_wrongbook_entries_verdict"), table_name="wrongbook_entries")
    op.drop_index(op.f("ix_wrongbook_entries_user_id"), table_name="wrongbook_entries")
    op.drop_index(op.f("ix_wrongbook_entries_submission_id"), table_name="wrongbook_entries")
    op.drop_index(op.f("ix_wrongbook_entries_problem_id"), table_name="wrongbook_entries")
    op.drop_table("wrongbook_entries")
    op.drop_index(op.f("ix_discussion_comments_discussion_id"), table_name="discussion_comments")
    op.drop_table("discussion_comments")
    op.drop_index(op.f("ix_discussions_problem_id"), table_name="discussions")
    op.drop_index(op.f("ix_discussions_knowledge_id"), table_name="discussions")
    op.drop_index(op.f("ix_discussions_author_id"), table_name="discussions")
    op.drop_table("discussions")
    # ### end Alembic commands ###
