"""add_user_lecture_reads

Revision ID: 20c16bf2008a
Revises: 3846ec5748ed
Create Date: 2026-08-11 10:54:13.352558

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20c16bf2008a"
down_revision: str | None = "3846ec5748ed"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_lecture_reads",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("lecture_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["knowledge_id"], ["knowledge_points.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["lecture_id"], ["lectures.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lecture_id", name="uq_user_lecture"),
    )
    op.create_index(op.f("ix_user_lecture_reads_knowledge_id"), "user_lecture_reads", ["knowledge_id"], unique=False)
    op.create_index(op.f("ix_user_lecture_reads_lecture_id"), "user_lecture_reads", ["lecture_id"], unique=False)
    op.create_index(op.f("ix_user_lecture_reads_user_id"), "user_lecture_reads", ["user_id"], unique=False)
    # 早期 seed_db 脚本创建的旧表；全新库上不存在，需幂等删除
    op.execute("DROP TABLE IF EXISTS seed_meta")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "seed_meta",
        sa.Column("key", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "imported_at", postgresql.TIMESTAMP(), server_default=sa.text("now()"), autoincrement=False, nullable=True
        ),
        sa.PrimaryKeyConstraint("key", name="seed_meta_pkey"),
    )
    op.drop_index(op.f("ix_user_lecture_reads_user_id"), table_name="user_lecture_reads")
    op.drop_index(op.f("ix_user_lecture_reads_lecture_id"), table_name="user_lecture_reads")
    op.drop_index(op.f("ix_user_lecture_reads_knowledge_id"), table_name="user_lecture_reads")
    op.drop_table("user_lecture_reads")
    # ### end Alembic commands ###
