"""add checkins and review_records

Revision ID: 5a75d97dbef9
Revises: 04936a68d35a
Create Date: 2026-08-10 06:14:18.222401

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a75d97dbef9"
down_revision: str | None = "04936a68d35a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "check_ins",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("check_date", sa.Date(), nullable=False),
        sa.Column("streak_days", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "check_date", name="uq_check_in_user_date"),
    )
    op.create_index(op.f("ix_check_ins_check_date"), "check_ins", ["check_date"], unique=False)
    op.create_index(op.f("ix_check_ins_user_id"), "check_ins", ["user_id"], unique=False)
    op.create_table(
        "review_records",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("knowledge_id", sa.UUID(), nullable=False),
        sa.Column(
            "stage",
            sa.Enum(
                "initial",
                "stage_1",
                "stage_2",
                "stage_3",
                "stage_4",
                "stage_5",
                "stage_6",
                "completed",
                name="review_stage",
            ),
            nullable=False,
        ),
        sa.Column("last_reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_review_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("review_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["knowledge_id"], ["knowledge_points.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "knowledge_id", name="uq_review_record_user_kp"),
    )
    op.create_index(op.f("ix_review_records_knowledge_id"), "review_records", ["knowledge_id"], unique=False)
    op.create_index(op.f("ix_review_records_next_review_at"), "review_records", ["next_review_at"], unique=False)
    op.create_index(op.f("ix_review_records_user_id"), "review_records", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_review_records_user_id"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_next_review_at"), table_name="review_records")
    op.drop_index(op.f("ix_review_records_knowledge_id"), table_name="review_records")
    op.drop_table("review_records")
    op.drop_index(op.f("ix_check_ins_user_id"), table_name="check_ins")
    op.drop_index(op.f("ix_check_ins_check_date"), table_name="check_ins")
    op.drop_table("check_ins")
    # ### end Alembic commands ###
